---
language: cpp
os:
  - linux
dist: focal
version: ~> 1.0

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

compiler:
  - clang
  - gcc

env:
  - CMAKE_GENERATOR=Ninja
  - CMAKE_GENERATOR="Unix Makefiles"

addons:
  apt:
    sources:
      - sourceline: "deb https://apt.kitware.com/ubuntu/ $TRAVIS_DIST main"
        key_url: "https://apt.kitware.com/keys/kitware-archive-latest.asc"
    packages:
      - clang
      - cmake
      - g++
      - make
      - ninja-build
      - pkg-config

jobs:
  include:
    - arch: arm64-graviton2
      compiler: clang
      virt: lxd
    - arch: arm64-graviton2
      compiler: gcc
      virt: lxd

script: |
  mkdir _build
  cd _build
  cmake \
    -DBUILD_DOCUMENTATION:BOOL=OFF \
    -DBUILD_TESTING:BOOL=ON \
    -DCMAKE_INSTALL_PREFIX:PATH=_install \
    -DENABLE_HARDENING:BOOL=OFF \
    -DENABLE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF \
    -DENABLE_OPENMP:BOOL=OFF \
    -DOUTPUT_TIME_AND_POSITIONS:BOOL=OFF \
    -DSEED_RANDOM_NUMBER_GENERATOR:BOOL=OFF \
    -DWARNINGS_AS_ERRORS:BOOL=ON \
    --warn-uninitialized \
    ..
  cmake --build .
  ctest .
  cmake --install .
