---
version: 2.0.{build}
os:
  - Visual Studio 2013
  - Visual Studio 2015
build_script:
  - md _build
  - cd _build
  - cmake -A x64 ..
  - ctest --build-config Release --extra-verbose --dashboard Experimental .
test: off
