#
# config.yml
# RVO2 Library
#
# SPDX-FileCopyrightText: 2008 University of North Carolina at Chapel Hill
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Please send all bug reports to <geom@cs.unc.edu>.
#
# The authors may be contacted via:
#
# Jur van den Berg, Stephen J. Guy, Jamie Snape, Ming C. Lin, Dinesh Manocha
# Dept. of Computer Science
# 201 S. Columbia St.
# Frederick P. Brooks, Jr. Computer Science Bldg.
# Chapel Hill, N.C. 27599-3175
# United States of America
#
# <https://gamma.cs.unc.edu/RVO2/>
#

---
version: 2.1

jobs:
  ubuntu:
    machine:
      image: ubuntu-2204:2022.10.2
    resource_class: arm.medium
    steps:
      - run:
          name: setup
          command: |
            sudo apt-get -qq -o APT::Acquire::Retries=4 update \
              || (sleep 15; apt-get -qq -o APT::Acquire::Retries=4 update)
            sudo apt-get -qq -o APT::Acquire::Retries=4 -o Dpkg::Use-Pty=0 --no-install-recommends install \
              ca-certificates \
              g++ \
              git \
              gnupg \
              make \
              pkg-config \
              wget
            wget -qO- https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
              | gpg --dearmor - \
              | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
            echo 'deb [arch=arm64 signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' \
              | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
            sudo apt-get -qq -o APT::Acquire::Retries=4 update \
              || (sleep 15; apt-get -qq -o APT::Acquire::Retries=4 update)
            sudo apt-get -qq -o APT::Acquire::Retries=4 -o Dpkg::Use-Pty=0 --no-install-recommends install \
              cmake
            sudo apt-get -qq -o Dpkg::Use-Pty=0 autoremove
            sudo rm -rf /var/lib/apt/lists/*
          environment:
            DEBIAN_FRONTEND: noninteractive
      - checkout
      - run:
          name: build test
          command: |
            mkdir _build
            cmake \
              -B _build \
              -DBUILD_DOCUMENTATION:BOOL=OFF \
              -DBUILD_TESTING:BOOL=ON \
              -DCMAKE_INSTALL_PREFIX:PATH=install \
              -DENABLE_HARDENING:BOOL=OFF \
              -DENABLE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF \
              -DENABLE_OPENMP:BOOL=OFF \
              -DOUTPUT_TIME_AND_POSITIONS:BOOL=OFF \
              -DSEED_RANDOM_NUMBER_GENERATOR:BOOL=OFF \
              -DWARNINGS_AS_ERRORS:BOOL=ON \
              -S . \
              --warn-uninitialized
            cmake --build _build
            ctest -E Roadmap --output-junit out.xml --test-dir _build --repeat after-timeout:3 .
            cmake --install _build
      - store_test_results:
          path: _build/out.xml

workflows:
  version: 2
  continuous:
    jobs:
      - ubuntu:
          filters:
            branches:
              only:
                - main
  weekly:
    triggers:
      - schedule:
          cron: '0 0 * * 4'
          filters:
            branches:
              only:
                - main
    jobs:
      - ubuntu
